// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQQvQHWFVz92TbOILXL4Mmg_iwXzd2Ktg',
    appId: '1:764567465724:web:37aa42e0fa447acab33179',
    messagingSenderId: '764567465724',
    projectId: 'myconcert-297e6',
    authDomain: 'myconcert-297e6.firebaseapp.com',
    storageBucket: 'myconcert-297e6.firebasestorage.app',
    measurementId: 'G-XFBZ9TV9DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA26m1iqf1YyYGSqiBVzmVhmwyRAnVriIc',
    appId: '1:764567465724:android:0040b7cf5481b85ab33179',
    messagingSenderId: '764567465724',
    projectId: 'myconcert-297e6',
    storageBucket: 'myconcert-297e6.firebasestorage.app',
  );
}
